# tests are generated by github copilot.

import unittest
from big_o_example import BigOExamples

class TestBigOExamples(unittest.TestCase):
    def setUp(self):
        self.examples = BigOExamples()

    def test_get_first_element(self):
        self.assertEqual(self.examples.get_first_element([1, 2, 3]), 1)
        self.assertEqual(self.examples.get_first_element(['a', 'b', 'c']), 'a')
        with self.assertRaises(IndexError):
            self.examples.get_first_element([])

    def test_binary_search(self):
        self.assertEqual(self.examples.binary_search([1, 2, 3, 4, 5], 3), 2)
        self.assertEqual(self.examples.binary_search([1, 2, 3, 4, 5], 6), -1)
        self.assertEqual(self.examples.binary_search([], 1), -1)
        self.assertEqual(self.examples.binary_search([1, 2, 3, 4, 5], 1), 0)
        self.assertEqual(self.examples.binary_search([1, 2, 3, 4, 5], 5), 4)

    def test_linear_search(self):
        self.assertEqual(self.examples.linear_search([1, 2, 3, 4, 5], 3), 2)
        self.assertEqual(self.examples.linear_search([1, 2, 3, 4, 5], 6), -1)
        self.assertEqual(self.examples.linear_search([], 1), -1)
        self.assertEqual(self.examples.linear_search([1, 2, 3, 4, 5], 1), 0)
        self.assertEqual(self.examples.linear_search([1, 2, 3, 4, 5], 5), 4)
        self.assertEqual(self.examples.linear_search([1], 2), -1)
        self.assertEqual(self.examples.linear_search([1], 1), 0)

    def test_merge_sort(self):
        arr = [12, 11, 13, 5, 6, 7]
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [5, 6, 7, 11, 12, 13])

        arr = []
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [])

        arr = [1]
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [1])

        arr = [5, 4, 3, 2, 1]
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [1, 2, 3, 4, 5])

        arr = [1, 2, 3, 4, 5]
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [1, 2, 3, 4, 5])

    def test_print_pairs(self):
        from io import StringIO
        from unittest.mock import patch
        
        # Test with a simple array
        test_array = [1, 2]
        expected_output = "1 ,  1\n1 ,  2\n2 ,  1\n2 ,  2\n"
        
        with patch('sys.stdout', new=StringIO()) as fake_out:
            self.examples.print_pairs(test_array)
            self.assertEqual(fake_out.getvalue(), expected_output)
        
        # Test with empty array
        with patch('sys.stdout', new=StringIO()) as fake_out:
            self.examples.print_pairs([])
            self.assertEqual(fake_out.getvalue(), "")
        
        # Test with single element array
        test_array = [1]
        expected_output = "1 ,  1\n"
        with patch('sys.stdout', new=StringIO()) as fake_out:
            self.examples.print_pairs(test_array)
            self.assertEqual(fake_out.getvalue(), expected_output)

        arr = [5, 2, 4, 1, 3, 2]
        self.examples.merge_sort(arr, 0, len(arr)-1)
        self.assertEqual(arr, [1, 2, 2, 3, 4, 5])

    def test_fib(self):
        # Test base cases
        self.assertEqual(self.examples.fib(0), 0)
        self.assertEqual(self.examples.fib(1), 1)
        
        # Test regular cases
        self.assertEqual(self.examples.fib(2), 1)  # 0 + 1
        self.assertEqual(self.examples.fib(3), 2)  # 1 + 1
        self.assertEqual(self.examples.fib(4), 3)  # 1 + 2
        self.assertEqual(self.examples.fib(5), 5)  # 2 + 3
        self.assertEqual(self.examples.fib(6), 8)  # 3 + 5
        self.assertEqual(self.examples.fib(7), 13) # 5 + 8
        
        # Test negative input - should handle like any other input based on implementation
        self.assertEqual(self.examples.fib(-1), -1)

if __name__ == '__main__':
    unittest.main()
